### ISSUE TITLE
User not deleted in LDAP

### ISSUE THREAD

**Issue by northboys** [ahaenggli/AzureAD-LDAP-wrapper#31]
**Describe the bug**
I tried to delete user in Azure AD but didn't delete in LDAP.

**Container configuration**
```
    environment:
      NODE_ENV: "production"
      LDAP_DOMAIN: "example.com"
      LDAP_BASEDN: "dc=example,dc=com"
      LDAP_BINDUSER: "test|test123"
      LDAP_PORT: "13389"
      LDAP_DEBUG: "true"
      LDAP_ALLOWCACHEDLOGINONFAILURE: "true"
      LDAP_SAMBANTPWD_MAXCACHETIME: "-1"
      AZURE_APP_ID: "xxxxxxxxxx"
      AZURE_TENANTID: "xxxxxxxxxx"
      AZURE_APP_SECRET: "xxxxxxxxxx"
      LDAP_SYNC_TIME: "15"
      DSM7: "false"
      GRAPH_FILTER_USERS: "userType eq 'Member'"
      GRAPH_FILTER_GROUPS: ""
```
